my_project_profile:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'etl_test'
      schema: 'main'
      schemas_and_paths:
        main: '/Users/denrobin0/Documents/data_learning/interview_work/data-testing-framework/etl_test.sqlite3'
      schema_directory: '/Users/denrobin0/Documents/data_learning/interview_work/data-testing-framework'